travis:
  secure:
    BINSTAR_TOKEN: R43uOdn4e0P7xSmwkFLFxVEr2oetGZS2m/uleTEIopZtVCUGEskVlyCR+VTqIpgKYMXv2MUs30Ip5eHc05GGsKwfTfzEKBzkYu8O0ja2GnMWmcHD6FVsFKlu+KfcE9DlJ1/i4vKuH2AAFFI1vSPaItpwUbQvxcaU6BdfouwOI/TvlskXrpea9Y1kpz3eA6uTo5ERqgSsTwpVhWaakEmXiyeCgFTvy7zxD2mmOXA77GRMTs7qmdqIkhkhIeIirGBxq8oGRZWyaTEWdMjYP/TpWk5uT3t3eyATY6yf0mZII2wHaKQxoQJ8DRBYyYdhrz1Rz77d4EDCkuM2Fx5WtB4djFq9QrIEKeQrD/SbdEv74GxJ4wWZKRUVTPBbVl+sroaYXEuOPY9bLIqWmvqg6QMvUaV/jY4i2JALm2sgOospXTDG+Jy6fvlHKtejaU1GtWagF/HgDDGA6njSTUH7LLkY6Y+9a3A3EC5psIW4GWviivhHnGfRery56iepaGFGJJA/Xye5Fdq+tc8JxE8IkNKCsPTeJjHw9hajJjRh7luDFleggC5aSMqQdLZccUQNbYrVaMdiITTvSQCE9et4NCHjX46Zs/GRwB6YT4wFq4tHP7UZkWpyDmESXgOytNde/1eRvPPOr1fe+fpTkmmnvkcUF+0AIStYTXZMY0xpIMEo5Dk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
